Fix locked in typedImplicit?
still failing: http4s/fs2/libretto/parboiled2

fs2 failure specific to ClassTag that could be special-cased.

[error] -- [E172] Type Error: /__w/dotty/dotty/community-build/community-projects/libretto/examples/src/main/scala/libretto/examples/PingPong.scala:79:98
[error] 79 |      .>(constVal("ping"))                 .to [  Val["ping"]                                    ] // (3)
[error]    |                                                                                                  ^
[error]    |Cannot prove that libretto.StarterKit.dsl.Val[String] =:= libretto.StarterKit.dsl.Val[("ping" : String)].
[error] one error found
[error] (examples / Compile / compileIncremental) Compilation failed

[error] -- [E007] Type Mismatch Error: /__w/dotty/dotty/community-build/community-projects/parboiled2/parboiled-core/src/test/scala/org/parboiled2/ActionSpec.scala:100:30
[error] 100 |        def targetRule = rule(push(1 :: "X" :: HNil) ~ run((i: Int, x: String) => (x.head - i).toChar) ~ EOI)
[error]     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Found:    org.parboiled2.Rule[org.parboiled2.support.hlist.HNil, Int :: String ::
[error]     |  org.parboiled2.support.hlist.HNil]
[error]     |Required: org.parboiled2.Rule[org.parboiled2.support.hlist.HNil, Char ::
[error]     |  org.parboiled2.support.hlist.HNil]
[error]     |
[error]     | longer explanation available when compiling with `-explain`
[error] -- [E007] Type Mismatch Error: /__w/dotty/dotty/community-build/community-projects/parboiled2/parboiled-core/src/test/scala/org/parboiled2/ReductionResetSpec.scala:43:8
[error] 43 |        run((_: String).toInt)
[error]    |        ^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    org.parboiled2.Rule[org.parboiled2.support.hlist.HNil,
[error]    |  org.parboiled2.support.hlist.HNil]
[error]    |Required: org.parboiled2.Rule[String :: org.parboiled2.support.hlist.HNil, Int ::
[error]    |  org.parboiled2.support.hlist.HNil]
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] -- [E007] Type Mismatch Error: /__w/dotty/dotty/community-build/community-projects/parboiled2/parboiled-core/src/test/scala/org/parboiled2/ReductionResetSpec.scala:48:8
[error] 48 |        run((_: Int).toString)
[error]    |        ^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    org.parboiled2.Rule[org.parboiled2.support.hlist.HNil,
[error]    |  org.parboiled2.support.hlist.HNil]
[error]    |Required: org.parboiled2.Rule[Int :: org.parboiled2.support.hlist.HNil, String ::
[error]    |  org.parboiled2.support.hlist.HNil]
[error]    |
[error]    | longer explanation available when compiling with `-explain`